AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120 